/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxsubmod.c
 *  subm:  PositionControllerPan
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  June 25, 2025
 *  time:  12:21:48 PM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* Standard include files */
#include <stdlib.h>

/* 20-sim include files */
#include "pan_xxmodel.h"
#include "pan_integ.h"
//#include "xxfuncs.h"
#include "pan_xxsubmod.h"

/* The submodel I/O variables */
PanInteger pan_number_of_inputs = 2;
PanInteger pan_number_of_outputs = 2;

/* the names of the submodel io variables
   uncomment this part if you need these names
PanString pan_input_names[] = {
	"in",
	"position"
,	NULL
};
PanString pan_output_names[] = {
	"corr",
	"out"
,	NULL
};
*/
/* This function sets the input variables from the input vector */
void PanCopyInputsToVariables (PanDouble *u)
{
	/* Copy the input vector to the input variables */
	pan_V[7] = u[0];		/* in */
	pan_V[8] = u[1];		/* position */

}

/* This function uses the output variables to fill the output vector */
void PanCopyVariablesToOutputs (PanDouble *y)
{
	/* Copy the output variables to the output vector */
	y[0] = 	pan_V[6];		/* corr */
	y[1] = 	pan_V[9];		/* out */

}

/* The initialization function for submodel */
void PanInitializeSubmodel (PanDouble *u, PanDouble *y, PanDouble t)
{
	/* Initialization phase (allocating memory) */
	pan_initialize = PanTRUE;
	pan_steps = 0;
	PanModelInitialize ();
	PanDiscreteInitialize ();

	/* Copy the inputs */
	pan_time = t;
	PanCopyInputsToVariables (u);

	/* Calculate the model for the first time */
	PanCalculateInitial ();
	PanCalculateStatic ();
	PanCalculateInput ();
	PanCalculateDynamic ();
	PanCalculateOutput ();

	/* Set the outputs */
	PanCopyVariablesToOutputs (y);

	/* End of initialization phase */
	pan_initialize = PanFALSE;
}

/* The function that calculates the submodel */
void PanCalculateSubmodel (PanDouble *u, PanDouble *y, PanDouble t)
{
	/* Copy the inputs */
	pan_time = t;
	PanCopyInputsToVariables (u);

	/* Calculate the model */
	PanCalculateInput ();
	PanDiscreteStep ();
	PanCalculateOutput ();

	/* Copy the outputs */
	PanCopyVariablesToOutputs (y);
}

/* The termination function for submodel */
void PanTerminateSubmodel (PanDouble *u, PanDouble *y, PanDouble t)
{
	/* Copy the inputs */
	pan_time = t;
	PanCopyInputsToVariables (u);

	/* Calculate the final model equations */
	PanCalculateFinal ();

	/* Set the outputs */
	PanCopyVariablesToOutputs (y);

	/* and terminate the model itself (releasing memory) */
	PanModelTerminate ();
	PanDiscreteTerminate ();
}

