/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxsubmod.h
 *  subm:  PositionControllerPan
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  June 25, 2025
 *  time:  12:21:48 PM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the xxmodel.c file
*/

#ifndef Pan_SUBMOD_H
#define Pan_SUBMOD_H

/* Our own include files */
#include "pan_xxmodel.h"

/* Submodel I/O variables */
extern PanInteger pan_number_of_inputs;
extern PanInteger pan_number_of_outputs;

/* The names of the variables as used in the arrays above */
extern PanString pan_input_names[];
extern PanString pan_output_names[];


/* The submodel functions */
void PanInitializeSubmodel (PanDouble *u, PanDouble *y, PanDouble t);
void PanCalculateSubmodel (PanDouble *u, PanDouble *y, PanDouble t);
void PanTerminateSubmodel (PanDouble *u, PanDouble *y, PanDouble t);
void PanCopyInputsToVariables (PanDouble *u);
void PanCopyVariablesToOutputs (PanDouble *y);

#endif

