/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxmodel.h
 *  subm:  PositionControllerPan
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  June 25, 2025
 *  time:  12:21:48 PM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the xxmodel.c file
*/

#ifndef Pan_MODEL_H
#define Pan_MODEL_H

/* Our own include files */
#include "xxtypes.h"

/* Simulation variables */
extern PanDouble pan_start_time;
extern PanDouble pan_finish_time;
extern PanDouble pan_step_size;
extern PanDouble pan_time;
extern PanInteger pan_steps;
extern PanBoolean pan_initialize;
extern PanBoolean pan_major;
extern PanBoolean pan_stop_simulation;

/* Model size constants */
#define pan_constants_size 0
#define pan_parameters_size 7
#define pan_initialvalues_size 3
#define pan_variables_size 10
#define pan_states_size 3

/* Variable arrays */
extern PanDouble pan_P[];
extern PanDouble pan_I[];
extern PanDouble pan_V[];
extern PanDouble pan_s[];
extern PanDouble pan_R[];


/* The names of the variables as used in the arrays above
   uncomment this if you need the names (see source file too)
extern PanString pan_parameter_names[];
extern PanString pan_initial_value_names[];
extern PanString pan_variable_names[];
extern PanString pan_state_names[];
extern PanString pan_rate_names[];
*/

/* Initialization methods */
/* Initialize complete model */
void PanModelInitialize (void);
/* Initialize specific model values */
void PanModelInitialize_parameters(void);
void PanModelInitialize_initialvalues(void);
void PanModelInitialize_states(void);
void PanModelInitialize_variables(void);
void PanModelTerminate (void);

/* Computation methods */
void PanCalculateInitial (void);
void PanCalculateStatic (void);
void PanCalculateInput (void);
void PanCalculateDynamic (void);
void PanCalculateOutput (void);
void PanCalculateFinal (void);


#endif

