/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxinteg.c
 *  subm:  PositionControllerPan
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  June 25, 2025
 *  time:  12:21:48 PM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* This file describes the integration methods
   that are supplied for computation.

   Currently the following methods are supported:
   * Discrete
   * Euler
   * RungeKutta2
   * RungeKutta4
   but it is easy for the user to add their own
   integration methods with these as examples.
*/

/* the system include files */
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* our own include files */
#include "pan_integ.h"
#include "pan_xxmodel.h"

/* global variables prototypes */
extern PanDouble pan_time;
extern PanDouble pan_step_size;

#define pan_STATE_SIZE 3

/*********************************************************************
 * Discrete integration method
 *********************************************************************/

/* the initialization of the Discrete integration method */
void PanDiscreteInitialize (void)
{
	/* nothing to be done */
	pan_major = PanTRUE;
}

/* the termination of the Discrete integration method */
void PanDiscreteTerminate (void)
{
	/* nothing to be done */
}

/* the Discrete integration method itself */
void PanDiscreteStep (void)
{
	PanInteger index;

	/* for each of the supplied states */
	for (index = 0; index < pan_STATE_SIZE; index++)
	{
		/* just a move of the new state */
		pan_s [index] = pan_R [index];
	}
	/* increment the simulation time */
	pan_time += pan_step_size;

	pan_major = PanTRUE;

	/* evaluate the dynamic part to calculate the new rates */
	PanCalculateDynamic ();
}

