/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxmodel.h
 *  subm:  PositionControllerPan
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  June 9, 2025
 *  time:  11:18:49 PM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the xxmodel.c file
*/

#ifndef PAN_MODEL_H
#define PAN_MODEL_H

/* Our own include files */
#include "xxtypes.h"

/* Simulation variables */
//extern XXDouble xx_start_time;
//extern XXDouble xx_finish_time;
//extern XXDouble xx_step_size;
//extern XXDouble xx_time;
//extern XXInteger xx_steps;
//extern XXBoolean xx_initialize;
//extern XXBoolean xx_major;
//extern XXBoolean xx_stop_simulation;

/* Model size constants */
#define pan_constants_size 0
#define pan_parameters_size 7
#define pan_initialvalues_size 3
#define pan_variables_size 10
#define pan_states_size 3

/* Variable arrays */
extern XXDouble pan_P[];
extern XXDouble pan_I[];
extern XXDouble pan_V[];
extern XXDouble pan_s[];
extern XXDouble pan_R[];

extern XXDouble pan_step_size;


/* The names of the variables as used in the arrays above
   uncomment this if you need the names (see source file too)
extern XXString xx_parameter_names[];
extern XXString xx_initial_value_names[];
extern XXString xx_variable_names[];
extern XXString xx_state_names[];
extern XXString xx_rate_names[];
*/

/* Initialization methods */
/* Initialize complete model */
void PanModelInitialize (void);
/* Initialize specific model values */
void PanModelInitialize_parameters(void);
void PanModelInitialize_initialvalues(void);
void PanModelInitialize_states(void);
void PanModelInitialize_variables(void);
void PanModelTerminate (void);

/* Computation methods */
void PanCalculateInitial (void);
void PanCalculateStatic (void);
void PanCalculateInput (void);
void PanCalculateDynamic (void);
void PanCalculateOutput (void);
void PanCalculateFinal (void);


#endif

