/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxmodel.h
 *  subm:  PositionControllerTilt
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  June 10, 2025
 *  time:  12:06:37 AM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the xxmodel.c file
*/


#ifndef TILT_MODEL_H
#define TILT_MODEL_H

#ifdef __cplusplus
extern "C" {
#endif

/* Our own include files */
#include "xxtypes.h"

/* Simulation variables */
//extern XXDouble xx_start_time;
//extern XXDouble xx_finish_time;
//extern XXDouble xx_step_size;
//extern XXDouble xx_time;
//extern XXInteger xx_steps;
//extern XXBoolean xx_initialize;
//extern XXBoolean xx_major;
//extern XXBoolean xx_stop_simulation;

/* Model size constants */
#define tilt_constants_size 0
#define tilt_parameters_size 7
#define tilt_initialvalues_size 3
#define tilt_variables_size 12
#define tilt_states_size 3

/* Variable arrays */
extern XXDouble tilt_P[];
extern XXDouble tilt_I[];
extern XXDouble tilt_V[];
extern XXDouble tilt_s[];
extern XXDouble tilt_R[];

extern XXDouble tilt_step_size;

/* The names of the variables as used in the arrays above
   uncomment this if you need the names (see source file too)
extern XXString xx_parameter_names[];
extern XXString xx_initial_value_names[];
extern XXString xx_variable_names[];
extern XXString xx_state_names[];
extern XXString xx_rate_names[];
*/

/* Initialization methods */
/* Initialize complete model */
void TiltModelInitialize (void);
/* Initialize specific model values */
void TiltModelInitialize_parameters(void);
void TiltModelInitialize_initialvalues(void);
void TiltModelInitialize_states(void);
void TiltModelInitialize_variables(void);
void TiltModelTerminate (void);

/* Computation methods */
void TiltCalculateInitial (void);
void TiltCalculateStatic (void);
void TiltCalculateInput (void);
void TiltCalculateDynamic (void);
void TiltCalculateOutput (void);
void TiltCalculateFinal (void);

#ifdef __cplusplus
}
#endif

#endif

