/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxsubmod.h
 *  subm:  PositionControllerTilt
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  June 25, 2025
 *  time:  12:22:27 PM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the xxmodel.c file
*/

#ifndef Tilt_SUBMOD_H
#define Tilt_SUBMOD_H

/* Our own include files */
#include "tilt_xxmodel.h"

/* Submodel I/O variables */
extern TiltInteger tilt_number_of_inputs;
extern TiltInteger tilt_number_of_outputs;

/* The names of the variables as used in the arrays above */
extern TiltString tilt_input_names[];
extern TiltString tilt_output_names[];


/* The submodel functions */
void TiltInitializeSubmodel (TiltDouble *u, TiltDouble *y, TiltDouble t);
void TiltCalculateSubmodel (TiltDouble *u, TiltDouble *y, TiltDouble t);
void TiltTerminateSubmodel (TiltDouble *u, TiltDouble *y, TiltDouble t);
void TiltCopyInputsToVariables (TiltDouble *u);
void TiltCopyVariablesToOutputs (TiltDouble *y);

#endif

