/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxsubmod.c
 *  subm:  PositionControllerTilt
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  June 25, 2025
 *  time:  12:22:27 PM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* Standard include files */
#include <stdlib.h>

/* 20-sim include files */
#include "tilt_xxmodel.h"
#include "tilt_integ.h"
#include "xxfuncs.h"
#include "tilt_xxsubmod.h"

/* The submodel I/O variables */
TiltInteger tilt_number_of_inputs = 3;
TiltInteger tilt_number_of_outputs = 1;

/* the names of the submodel io variables
   uncomment this part if you need these names
TiltString tilt_input_names[] = {
	"corr",
	"in",
	"position"
,	NULL
};
TiltString tilt_output_names[] = {
	"out"
,	NULL
};
*/
/* This function sets the input variables from the input vector */
void TiltCopyInputsToVariables (TiltDouble *u)
{
	/* Copy the input vector to the input variables */
	tilt_V[8] = u[0];		/* corr */
	tilt_V[9] = u[1];		/* in */
	tilt_V[10] = u[2];		/* position */

}

/* This function uses the output variables to fill the output vector */
void TiltCopyVariablesToOutputs (TiltDouble *y)
{
	/* Copy the output variables to the output vector */
	y[0] = 	tilt_V[11];		/* out */

}

/* The initialization function for submodel */
void TiltInitializeSubmodel (TiltDouble *u, TiltDouble *y, TiltDouble t)
{
	/* Initialization phase (allocating memory) */
	tilt_initialize = TiltTRUE;
	tilt_steps = 0;
	TiltModelInitialize ();
	TiltDiscreteInitialize ();

	/* Copy the inputs */
	tilt_time = t;
	TiltCopyInputsToVariables (u);

	/* Calculate the model for the first time */
	TiltCalculateInitial ();
	TiltCalculateStatic ();
	TiltCalculateInput ();
	TiltCalculateDynamic ();
	TiltCalculateOutput ();

	/* Set the outputs */
	TiltCopyVariablesToOutputs (y);

	/* End of initialization phase */
	tilt_initialize = TiltFALSE;
}

/* The function that calculates the submodel */
void TiltCalculateSubmodel (TiltDouble *u, TiltDouble *y, TiltDouble t)
{
	/* Copy the inputs */
	tilt_time = t;
	TiltCopyInputsToVariables (u);

	/* Calculate the model */
	TiltCalculateInput ();
	TiltDiscreteStep ();
	TiltCalculateOutput ();

	/* Copy the outputs */
	TiltCopyVariablesToOutputs (y);
}

/* The termination function for submodel */
void TiltTerminateSubmodel (TiltDouble *u, TiltDouble *y, TiltDouble t)
{
	/* Copy the inputs */
	tilt_time = t;
	TiltCopyInputsToVariables (u);

	/* Calculate the final model equations */
	TiltCalculateFinal ();

	/* Set the outputs */
	TiltCopyVariablesToOutputs (y);

	/* and terminate the model itself (releasing memory) */
	TiltModelTerminate ();
	TiltDiscreteTerminate ();
}

