/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxinteg.c
 *  subm:  PositionControllerPan
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  June 25, 2025
 *  time:  12:21:48 PM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* This file describes the integration methods
   that are supplied for computation.

   Currently the following methods are supported:
   * Discrete
   * Euler
   * RungeKutta2
   * RungeKutta4
   but it is easy for the user to add their own
   integration methods with these as examples.
*/

/* the system include files */
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* our own include files */
#include "tilt_integ.h"
#include "tilt_xxmodel.h"

/* global variables prototypes */
extern TiltDouble tilt_time;
extern TiltDouble tilt_step_size;

#define tilt_STATE_SIZE 3

/*********************************************************************
 * Discrete integration method
 *********************************************************************/

/* the initialization of the Discrete integration method */
void TiltDiscreteInitialize (void)
{
	/* nothing to be done */
	tilt_major = TiltTRUE;
}

/* the termination of the Discrete integration method */
void TiltDiscreteTerminate (void)
{
	/* nothing to be done */
}

/* the Discrete integration method itself */
void TiltDiscreteStep (void)
{
	TiltInteger index;

	/* for each of the supplied states */
	for (index = 0; index < tilt_STATE_SIZE; index++)
	{
		/* just a move of the new state */
		tilt_s [index] = tilt_R [index];
	}
	/* increment the simulation time */
	tilt_time += tilt_step_size;

	tilt_major = TiltTRUE;

	/* evaluate the dynamic part to calculate the new rates */
	TiltCalculateDynamic ();
}

