/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxinteg.h
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  June 25, 2025
 *  time:  12:21:48 PM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* This file describes the integration methods
that are supplied for computation.

   Currently the following methods are supported:
   * Euler
   * RungeKutta2
   * RungeKutta4
   but it is easy for the user to add their own
   integration methods with these two as an example.
*/

#ifndef TILT_INTEG_H
#define TILT_INTEG_H

/* 20-sim include files */
#include"../common/xxtypes.h"

/* the chosen integration method */
#define Discrete_METHOD

/* the integration methods */
void TiltDiscreteInitialize (void);
void TiltDiscreteTerminate (void);
void TiltDiscreteStep (void);

extern TiltBoolean tilt_major;

#endif

