/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxmodel.h
 *  subm:  PositionControllerTilt
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  June 25, 2025
 *  time:  12:22:27 PM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the xxmodel.c file
*/

#ifndef Tilt_MODEL_H
#define Tilt_MODEL_H

/* Our own include files */
#include "../common/xxtypes.h"

/* Simulation variables */
extern TiltDouble tilt_start_time;
extern TiltDouble tilt_finish_time;
extern TiltDouble tilt_step_size;
extern TiltDouble tilt_time;
extern TiltInteger tilt_steps;
extern TiltBoolean tilt_initialize;
extern TiltBoolean tilt_major;
extern TiltBoolean tilt_stop_simulation;

/* Model size constants */
#define tilt_constants_size 0
#define tilt_parameters_size 7
#define tilt_initialvalues_size 3
#define tilt_variables_size 12
#define tilt_states_size 3

/* Variable arrays */
extern TiltDouble tilt_P[];
extern TiltDouble tilt_I[];
extern TiltDouble tilt_V[];
extern TiltDouble tilt_s[];
extern TiltDouble tilt_R[];


/* The names of the variables as used in the arrays above
   uncomment this if you need the names (see source file too)
extern TiltString tilt_parameter_names[];
extern TiltString tilt_initial_value_names[];
extern TiltString tilt_variable_names[];
extern TiltString tilt_state_names[];
extern TiltString tilt_rate_names[];
*/

/* Initialization methods */
/* Initialize complete model */
void TiltModelInitialize (void);
/* Initialize specific model values */
void TiltModelInitialize_parameters(void);
void TiltModelInitialize_initialvalues(void);
void TiltModelInitialize_states(void);
void TiltModelInitialize_variables(void);
void TiltModelTerminate (void);

/* Computation methods */
void TiltCalculateInitial (void);
void TiltCalculateStatic (void);
void TiltCalculateInput (void);
void TiltCalculateDynamic (void);
void TiltCalculateOutput (void);
void TiltCalculateFinal (void);


#endif

